// flow-typed signature: 13fb8f3ca840690092da25fb9d4008b4
// flow-typed version: <<STUB>>/eslint-plugin-relay_v0.0.8/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-relay/eslint-plugin-relay' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-relay/eslint-plugin-relay.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/eslint-plugin-relay'>;
}
