// flow-typed signature: 0c5b9ed911581feda9d8491ccd70a7ff
// flow-typed version: <<STUB>>/preact-emotion_v^8.0.12/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-emotion/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'preact-emotion/dist/index.es' {
  declare module.exports: any;
}

declare module 'preact-emotion/macro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-emotion/dist/index.cjs.js' {
  declare module.exports: $Exports<'preact-emotion/dist/index.cjs'>;
}
declare module 'preact-emotion/dist/index.es.js' {
  declare module.exports: $Exports<'preact-emotion/dist/index.es'>;
}
declare module 'preact-emotion/macro.js' {
  declare module.exports: $Exports<'preact-emotion/macro'>;
}
