// flow-typed signature: 25b637102f229aeab6cba1c2bbbb63da
// flow-typed version: <<STUB>>/preact-cli_v^2.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-cli/babel' {
  declare module.exports: any;
}

declare module 'preact-cli/check' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/build' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/create' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/list' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/watch' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/components/async' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/index' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/async-command' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/babel-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/entry' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/logo' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/output-hooks' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/setup' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/ssl-cert' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/async-component-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/dummy-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/polyfills' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/prerender' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/proxy-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/push-manifest' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/render-html-plugin' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/run-webpack' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/transform-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/webpack-base-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/webpack-client-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/webpack-server-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-cli/babel.js' {
  declare module.exports: $Exports<'preact-cli/babel'>;
}
declare module 'preact-cli/check.js' {
  declare module.exports: $Exports<'preact-cli/check'>;
}
declare module 'preact-cli/lib/commands/build.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/build'>;
}
declare module 'preact-cli/lib/commands/create.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/create'>;
}
declare module 'preact-cli/lib/commands/list.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/list'>;
}
declare module 'preact-cli/lib/commands/serve.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/serve'>;
}
declare module 'preact-cli/lib/commands/watch.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/watch'>;
}
declare module 'preact-cli/lib/components/async.js' {
  declare module.exports: $Exports<'preact-cli/lib/components/async'>;
}
declare module 'preact-cli/lib/index.js' {
  declare module.exports: $Exports<'preact-cli/lib/index'>;
}
declare module 'preact-cli/lib/lib/async-command.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/async-command'>;
}
declare module 'preact-cli/lib/lib/babel-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/babel-config'>;
}
declare module 'preact-cli/lib/lib/entry.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/entry'>;
}
declare module 'preact-cli/lib/lib/logo.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/logo'>;
}
declare module 'preact-cli/lib/lib/output-hooks.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/output-hooks'>;
}
declare module 'preact-cli/lib/lib/setup.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/setup'>;
}
declare module 'preact-cli/lib/lib/ssl-cert.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/ssl-cert'>;
}
declare module 'preact-cli/lib/lib/webpack/async-component-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/async-component-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/dummy-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/dummy-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/polyfills.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/polyfills'>;
}
declare module 'preact-cli/lib/lib/webpack/prerender.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/prerender'>;
}
declare module 'preact-cli/lib/lib/webpack/proxy-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/proxy-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/push-manifest.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/push-manifest'>;
}
declare module 'preact-cli/lib/lib/webpack/render-html-plugin.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/render-html-plugin'>;
}
declare module 'preact-cli/lib/lib/webpack/run-webpack.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/run-webpack'>;
}
declare module 'preact-cli/lib/lib/webpack/transform-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/transform-config'>;
}
declare module 'preact-cli/lib/lib/webpack/webpack-base-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/webpack-base-config'>;
}
declare module 'preact-cli/lib/lib/webpack/webpack-client-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/webpack-client-config'>;
}
declare module 'preact-cli/lib/lib/webpack/webpack-server-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/webpack-server-config'>;
}
declare module 'preact-cli/lib/util.js' {
  declare module.exports: $Exports<'preact-cli/lib/util'>;
}
