// flow-typed signature: db1f6f37f47cd70fb2cdd0c20e3ebf1c
// flow-typed version: <<STUB>>/preact-cli_v^1.4.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-cli/check' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/empty/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/full/src/components/app' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/full/src/components/header/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/full/src/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/full/src/routes/home/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/full/src/routes/profile/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/build/bundle.773ab' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/build/polyfills.dea62' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/build/route-home.chunk.43510' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/build/route-profile.chunk.36ce9' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/build/ssr-build/ssr-bundle' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/build/sw' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/components/header/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/routes/home/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/root/routes/profile/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/simple/build/bundle' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/simple/build/polyfills.chunk.0aa70d5cfc8a5178da31' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/simple/build/sw' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/simple/index' {
  declare module.exports: any;
}

declare module 'preact-cli/examples/simple/result' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/build' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/create' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/commands/watch' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/components/async' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/index' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/async-command' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/babel-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/entry' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/logo' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/output-hooks' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/setup' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/shell' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/ssl-cert' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/async-component-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/dependency-install-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/dummy-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/polyfills' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/prerender' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/proxy-loader' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/push-manifest' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/run-webpack' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/transform-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/webpack-base-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/webpack-client-config' {
  declare module.exports: any;
}

declare module 'preact-cli/lib/lib/webpack/webpack-server-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-cli/check.js' {
  declare module.exports: $Exports<'preact-cli/check'>;
}
declare module 'preact-cli/examples/empty/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/empty/index'>;
}
declare module 'preact-cli/examples/full/src/components/app.js' {
  declare module.exports: $Exports<'preact-cli/examples/full/src/components/app'>;
}
declare module 'preact-cli/examples/full/src/components/header/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/full/src/components/header/index'>;
}
declare module 'preact-cli/examples/full/src/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/full/src/index'>;
}
declare module 'preact-cli/examples/full/src/routes/home/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/full/src/routes/home/index'>;
}
declare module 'preact-cli/examples/full/src/routes/profile/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/full/src/routes/profile/index'>;
}
declare module 'preact-cli/examples/root/build/bundle.773ab.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/build/bundle.773ab'>;
}
declare module 'preact-cli/examples/root/build/polyfills.dea62.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/build/polyfills.dea62'>;
}
declare module 'preact-cli/examples/root/build/route-home.chunk.43510.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/build/route-home.chunk.43510'>;
}
declare module 'preact-cli/examples/root/build/route-profile.chunk.36ce9.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/build/route-profile.chunk.36ce9'>;
}
declare module 'preact-cli/examples/root/build/ssr-build/ssr-bundle.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/build/ssr-build/ssr-bundle'>;
}
declare module 'preact-cli/examples/root/build/sw.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/build/sw'>;
}
declare module 'preact-cli/examples/root/components/header/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/components/header/index'>;
}
declare module 'preact-cli/examples/root/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/index'>;
}
declare module 'preact-cli/examples/root/routes/home/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/routes/home/index'>;
}
declare module 'preact-cli/examples/root/routes/profile/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/root/routes/profile/index'>;
}
declare module 'preact-cli/examples/simple/build/bundle.js' {
  declare module.exports: $Exports<'preact-cli/examples/simple/build/bundle'>;
}
declare module 'preact-cli/examples/simple/build/polyfills.chunk.0aa70d5cfc8a5178da31.js' {
  declare module.exports: $Exports<'preact-cli/examples/simple/build/polyfills.chunk.0aa70d5cfc8a5178da31'>;
}
declare module 'preact-cli/examples/simple/build/sw.js' {
  declare module.exports: $Exports<'preact-cli/examples/simple/build/sw'>;
}
declare module 'preact-cli/examples/simple/index.js' {
  declare module.exports: $Exports<'preact-cli/examples/simple/index'>;
}
declare module 'preact-cli/examples/simple/result.js' {
  declare module.exports: $Exports<'preact-cli/examples/simple/result'>;
}
declare module 'preact-cli/lib/commands/build.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/build'>;
}
declare module 'preact-cli/lib/commands/create.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/create'>;
}
declare module 'preact-cli/lib/commands/serve.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/serve'>;
}
declare module 'preact-cli/lib/commands/watch.js' {
  declare module.exports: $Exports<'preact-cli/lib/commands/watch'>;
}
declare module 'preact-cli/lib/components/async.js' {
  declare module.exports: $Exports<'preact-cli/lib/components/async'>;
}
declare module 'preact-cli/lib/index.js' {
  declare module.exports: $Exports<'preact-cli/lib/index'>;
}
declare module 'preact-cli/lib/lib/async-command.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/async-command'>;
}
declare module 'preact-cli/lib/lib/babel-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/babel-config'>;
}
declare module 'preact-cli/lib/lib/entry.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/entry'>;
}
declare module 'preact-cli/lib/lib/logo.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/logo'>;
}
declare module 'preact-cli/lib/lib/output-hooks.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/output-hooks'>;
}
declare module 'preact-cli/lib/lib/setup.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/setup'>;
}
declare module 'preact-cli/lib/lib/shell.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/shell'>;
}
declare module 'preact-cli/lib/lib/ssl-cert.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/ssl-cert'>;
}
declare module 'preact-cli/lib/lib/webpack/async-component-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/async-component-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/dependency-install-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/dependency-install-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/dummy-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/dummy-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/polyfills.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/polyfills'>;
}
declare module 'preact-cli/lib/lib/webpack/prerender.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/prerender'>;
}
declare module 'preact-cli/lib/lib/webpack/proxy-loader.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/proxy-loader'>;
}
declare module 'preact-cli/lib/lib/webpack/push-manifest.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/push-manifest'>;
}
declare module 'preact-cli/lib/lib/webpack/run-webpack.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/run-webpack'>;
}
declare module 'preact-cli/lib/lib/webpack/transform-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/transform-config'>;
}
declare module 'preact-cli/lib/lib/webpack/webpack-base-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/webpack-base-config'>;
}
declare module 'preact-cli/lib/lib/webpack/webpack-client-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/webpack-client-config'>;
}
declare module 'preact-cli/lib/lib/webpack/webpack-server-config.js' {
  declare module.exports: $Exports<'preact-cli/lib/lib/webpack/webpack-server-config'>;
}
