// flow-typed signature: 6c8d09557b55511a632d89af75a6accd
// flow-typed version: <<STUB>>/preact-redux_v^2.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-redux/dist/preact-redux.esm' {
  declare module.exports: any;
}

declare module 'preact-redux/dist/preact-redux' {
  declare module.exports: any;
}

declare module 'preact-redux/dist/preact-redux.min' {
  declare module.exports: any;
}

declare module 'preact-redux/src/compat' {
  declare module.exports: any;
}

declare module 'preact-redux/src/empty' {
  declare module.exports: any;
}

declare module 'preact-redux/src/index' {
  declare module.exports: any;
}

declare module 'preact-redux/src/prop-types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-redux/dist/preact-redux.esm.js' {
  declare module.exports: $Exports<'preact-redux/dist/preact-redux.esm'>;
}
declare module 'preact-redux/dist/preact-redux.js' {
  declare module.exports: $Exports<'preact-redux/dist/preact-redux'>;
}
declare module 'preact-redux/dist/preact-redux.min.js' {
  declare module.exports: $Exports<'preact-redux/dist/preact-redux.min'>;
}
declare module 'preact-redux/src/compat.js' {
  declare module.exports: $Exports<'preact-redux/src/compat'>;
}
declare module 'preact-redux/src/empty.js' {
  declare module.exports: $Exports<'preact-redux/src/empty'>;
}
declare module 'preact-redux/src/index.js' {
  declare module.exports: $Exports<'preact-redux/src/index'>;
}
declare module 'preact-redux/src/prop-types.js' {
  declare module.exports: $Exports<'preact-redux/src/prop-types'>;
}
