// flow-typed signature: 13d9abc802e827566b357819199165c8
// flow-typed version: <<STUB>>/reconnecting-websocket_v^4.1.10/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reconnecting-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reconnecting-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reconnecting-websocket/dist/reconnecting-websocket-amd' {
  declare module.exports: any;
}

declare module 'reconnecting-websocket/dist/reconnecting-websocket-cjs' {
  declare module.exports: any;
}

declare module 'reconnecting-websocket/dist/reconnecting-websocket-iife' {
  declare module.exports: any;
}

declare module 'reconnecting-websocket/dist/reconnecting-websocket-iife.min' {
  declare module.exports: any;
}

declare module 'reconnecting-websocket/dist/reconnecting-websocket-mjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reconnecting-websocket/dist/reconnecting-websocket-amd.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/reconnecting-websocket-amd'>;
}
declare module 'reconnecting-websocket/dist/reconnecting-websocket-cjs.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/reconnecting-websocket-cjs'>;
}
declare module 'reconnecting-websocket/dist/reconnecting-websocket-iife.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/reconnecting-websocket-iife'>;
}
declare module 'reconnecting-websocket/dist/reconnecting-websocket-iife.min.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/reconnecting-websocket-iife.min'>;
}
declare module 'reconnecting-websocket/dist/reconnecting-websocket-mjs.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/reconnecting-websocket-mjs'>;
}
