// flow-typed signature: 326add8522c80326da565b19846df238
// flow-typed version: <<STUB>>/reconnecting-websocket_v^3.2.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reconnecting-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reconnecting-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reconnecting-websocket/dist/index' {
  declare module.exports: any;
}

declare module 'reconnecting-websocket/dist/reconnecting-websocket.amd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reconnecting-websocket/dist/index.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/index'>;
}
declare module 'reconnecting-websocket/dist/reconnecting-websocket.amd.js' {
  declare module.exports: $Exports<'reconnecting-websocket/dist/reconnecting-websocket.amd'>;
}
