// flow-typed signature: ded5ccfe5a2a2f4533926c21c6942100
// flow-typed version: <<STUB>>/tmi.js_v^1.2.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmi.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmi.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmi.js/lib/api' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/client' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/commands' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/events' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/logger' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/parser' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/timer' {
  declare module.exports: any;
}

declare module 'tmi.js/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmi.js/index' {
  declare module.exports: $Exports<'tmi.js'>;
}
declare module 'tmi.js/index.js' {
  declare module.exports: $Exports<'tmi.js'>;
}
declare module 'tmi.js/lib/api.js' {
  declare module.exports: $Exports<'tmi.js/lib/api'>;
}
declare module 'tmi.js/lib/client.js' {
  declare module.exports: $Exports<'tmi.js/lib/client'>;
}
declare module 'tmi.js/lib/commands.js' {
  declare module.exports: $Exports<'tmi.js/lib/commands'>;
}
declare module 'tmi.js/lib/events.js' {
  declare module.exports: $Exports<'tmi.js/lib/events'>;
}
declare module 'tmi.js/lib/logger.js' {
  declare module.exports: $Exports<'tmi.js/lib/logger'>;
}
declare module 'tmi.js/lib/parser.js' {
  declare module.exports: $Exports<'tmi.js/lib/parser'>;
}
declare module 'tmi.js/lib/timer.js' {
  declare module.exports: $Exports<'tmi.js/lib/timer'>;
}
declare module 'tmi.js/lib/utils.js' {
  declare module.exports: $Exports<'tmi.js/lib/utils'>;
}
