// flow-typed signature: f6f5c8db28b329d009daa9fea15d1838
// flow-typed version: <<STUB>>/uws_v^10.148.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uws' {
  declare module.exports: any;
}
