// flow-typed signature: 3bdc4c5c3e146b6f672dc9ce9bd8cad4
// flow-typed version: <<STUB>>/uws_v^8.14.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uws/uws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uws/uws.js' {
  declare module.exports: $Exports<'uws/uws'>;
}
