// flow-typed signature: 7f8fdf0aac6f9946bd13a160b86061e9
// flow-typed version: <<STUB>>/uws_v^10.148.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uws' {
  declare module.exports: any;
}
