name: nodejs
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm
      run: |
        npm install -g npm
        npm --version
    - name: Install dependencies
      run: npm ci
    - name: Validate
      run: npm run validate
      env:
        CI: true
    - name: Size
      run: npm run test:size
