name: nodejs
on: [pull_request, push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm
      run: |
        npm install -g npm
        npm --version
    - name: Install dependencies
      uses: bahmutov/npm-install@v1.10.2
    - name: Validate
      run: npm run validate
      env:
        CI: true
    - name: Size
      run: npm run test:size
